//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clicher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Save : global::System.Configuration.ApplicationSettingsBase {
        
        private static Save defaultInstance = ((Save)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Save())));
        
        public static Save Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double bani {
            get {
                return ((double)(this["bani"]));
            }
            set {
                this["bani"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double upgrade_price {
            get {
                return ((double)(this["upgrade_price"]));
            }
            set {
                this["upgrade_price"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double upgrade_price_dps {
            get {
                return ((double)(this["upgrade_price_dps"]));
            }
            set {
                this["upgrade_price_dps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double dmg_multiplier {
            get {
                return ((double)(this["dmg_multiplier"]));
            }
            set {
                this["dmg_multiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double dmg_total {
            get {
                return ((double)(this["dmg_total"]));
            }
            set {
                this["dmg_total"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double dps {
            get {
                return ((double)(this["dps"]));
            }
            set {
                this["dps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double dpc {
            get {
                return ((double)(this["dpc"]));
            }
            set {
                this["dpc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool timer1 {
            get {
                return ((bool)(this["timer1"]));
            }
            set {
                this["timer1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool timerdps {
            get {
                return ((bool)(this["timerdps"]));
            }
            set {
                this["timerdps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool pornit {
            get {
                return ((bool)(this["pornit"]));
            }
            set {
                this["pornit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lblAfisajCurrentDMG {
            get {
                return ((string)(this["lblAfisajCurrentDMG"]));
            }
            set {
                this["lblAfisajCurrentDMG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lblUpgradePrice {
            get {
                return ((string)(this["lblUpgradePrice"]));
            }
            set {
                this["lblUpgradePrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lblAfisareDPS {
            get {
                return ((string)(this["lblAfisareDPS"]));
            }
            set {
                this["lblAfisareDPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lblAfisareDMGperclick {
            get {
                return ((string)(this["lblAfisareDMGperclick"]));
            }
            set {
                this["lblAfisareDMGperclick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lblPriceDPS {
            get {
                return ((string)(this["lblPriceDPS"]));
            }
            set {
                this["lblPriceDPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double count_apasari {
            get {
                return ((double)(this["count_apasari"]));
            }
            set {
                this["count_apasari"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double exp_act {
            get {
                return ((double)(this["exp_act"]));
            }
            set {
                this["exp_act"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double exp_nec {
            get {
                return ((double)(this["exp_nec"]));
            }
            set {
                this["exp_nec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int level {
            get {
                return ((int)(this["level"]));
            }
            set {
                this["level"] = value;
            }
        }
    }
}
