//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clicher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Salvare : global::System.Configuration.ApplicationSettingsBase {
        
        private static Salvare defaultInstance = ((Salvare)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Salvare())));
        
        public static Salvare Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double bani {
            get {
                return ((double)(this["bani"]));
            }
            set {
                this["bani"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double upgrade_price {
            get {
                return ((double)(this["upgrade_price"]));
            }
            set {
                this["upgrade_price"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double upgrade_price_dps {
            get {
                return ((double)(this["upgrade_price_dps"]));
            }
            set {
                this["upgrade_price_dps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double dmg_multiplier {
            get {
                return ((double)(this["dmg_multiplier"]));
            }
            set {
                this["dmg_multiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double dmg_total {
            get {
                return ((double)(this["dmg_total"]));
            }
            set {
                this["dmg_total"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double dps {
            get {
                return ((double)(this["dps"]));
            }
            set {
                this["dps"] = value;
            }
        }
    }
}
